server:
  port: ${PORT:8080}
spring:
  sql:
    init:
      mode: always #For generate fakeData with data.sql file
  application:
    name: FilmApp
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/filmapp}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:password}
  jpa:
    open-in-view: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    #      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#    show-sql: ${SHOW_SQL:true}
  hateoas:
    use-hal-as-default-json-media-type: false
  data:
    web:
      pageable:
        max-page-size: 50
